# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20160501_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='name',
            new_name='site_name',
        ),
    ]
