# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20160501_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 1, 16, 30, 53, 613151, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
