# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20160502_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='name_text',
        ),
    ]
