# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20160502_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_name',
            new_name='name',
        ),
    ]
